<?php

namespace App\Criteria;

use Psr\Http\Message\UriInterface;

/**
 * filters urls if they are too similar to each other.
 *
 * Class ValidUrlCriteria
 * @package App\CrawlLinkCriteria
 */
class CriteriaNonSimilar extends LoggableCriteria
{
    /** @var string */
    protected $lastUrl = '';

    /** @var int */
    protected $similarUrls = 0;

    /**
     * @param UriInterface $uri
     *
     * @return bool
     */
    public function meetCriteria(UriInterface $uri): bool
    {
        if (false === $this->similarUrlCheck($uri->getPath())) {
            return true;
        }

        return false;
    }

    /**
     * Get Levenstein distance for url and decide if crawler is hopping autogenerated urls.
     *
     * @param string $url
     *
     * @return int
     */
    protected function similarUrlCheck(string $url)
    {
        $distance = levenshtein($url, $this->lastUrl);

        $this->lastUrl = $url;

        if (2 >= $distance && $this->similarUrls >= 10) {
            $this->logger->alert(
                sprintf("Url's to similar. current: %s, previous: %s  ", $url, $this->lastUrl)
            );

            return true;
        } elseif (2 >= $distance) {
            $this->similarUrls++;
        } else {
            $this->similarUrls = 0;
        }

        return false;
    }
}