<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Website;
use App\Entity\CrawlLink;

/**
 * CrawlLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlLinkRepository extends EntityRepository
{
    /**
     * Check if link is already in database.
     *
     * @param Website $website
     *
     * @return mixed
     */
    public function getAllUrls(Website $website)
    {
        return $this->createQueryBuilder('l')
            ->select('l.link')
            ->getQuery()
            ->getResult();
    }

    /**
     * Get array of uncrawled crawl links.
     *
     * @param Website $website
     *
     * @return CrawlLink[]
     */
    public function getUnCrawledLinks(Website $website)
    {
        return $this->createQueryBuilder('l')
            ->select()
            ->where('l.website = :website')
            ->setParameter('website', $website)
            ->andWhere('l.crawled = :crawled')
            ->setParameter('crawled', false)
            ->getQuery()
            ->getResult();
    }
}
