<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use App\Entity\Website;
use App\Entity\CrawlLink;

/**
 * CrawlLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlLinkRepository extends EntityRepository
{
    /**
     * Get all url's from a websites CrawlLinks and return in an array.
     *
     * @param Website $website
     *
     * @return mixed
     */
    public function getAllUrls(Website $website)
    {
        $roughResults = $this->createQueryBuilder('l')
            ->select('l.link')
            ->where('l.website = :website')
            ->setParameter('website', $website)
            ->getQuery()
            ->getResult();

        $result = [];
        foreach ($roughResults as $roughResult) {
            $result[] = $roughResult['link'];
        }

        return $result;
    }

    /**
     * Get array of uncrawled crawl links.
     *
     * @param Website $website
     *
     * @return CrawlLink[]
     */
    public function getUnCrawledLinks(Website $website): array
    {
        return $this->createQueryBuilder('l')
            ->select()
            ->where('l.website = :website')
            ->setParameter('website', $website)
            ->andWhere('l.crawled = :crawled')
            ->setParameter('crawled', false)
            ->getQuery()
            ->getResult();
    }

    /**
     * Get array most proven crawl links.
     *
     * @param Website $website
     * @param int     $avgNewLinks
     *
     * @return CrawlLink[]
     */
    public function getEfficientUrls(Website $website, int $avgNewLinks)
    {
        return $this->createQueryBuilder('l')
            ->select()
            ->where('l.website = :website')
            ->setParameter('website', $website)
            ->andWhere('l.crawlSuccesses / l.crawlCount >= :avgNewLinks')
            ->setParameter('avgNewLinks', $avgNewLinks)
            ->getQuery()
            ->getResult();
    }
}
