crawler:
  websites:
    -
      ignorePageUrlsWith:
        - archive
        - test
      name: "IJssel en Lekstreek (Capelle)"
    -
      ignorePageUrlsWith:
        - archive
        - test
      name: "test"